### ISSUE TITLE
Q5 test cases issue

### ISSUE THREAD

**Issue by raghavTinker** [Concept-Team/e-box-UTA018#9]
Only 88% test cases passing. Constructor destructor unit => i-Design

**Comment by hari01584** [comment]
I believe its an ebox error, Cant find any solution because the test script seems incorrect, My guess is that the test script of ebox doesnt have '''cin.ignore()''' therefore it skips out things and not all testcase are passing! Do correct me if i am wrong here.

**Comment by raghavTinker** [comment]
Yep the placement is the most probable thing. The code on the repo is fine though.

Will close the issue
